import { randomUUID, createHash } from "node:crypto";
import { mkdir, readFile, writeFile, unlink } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

export interface SavedFile {
  storageKey: string;
  sizeBytes: number;
  sha256: string;
}

export interface StorageProvider {
  saveFile(input: { buffer: Buffer; userId: string; originalName: string }): Promise<SavedFile>;
  readFile(storageKey: string): Promise<Buffer>;
  deleteFile(storageKey: string): Promise<void>;
}

/**
 * Files are never served from a public path — storageKey is an opaque
 * identifier resolved only through readFile(), which the API/worker call
 * server-side. The only client-facing access path is a short-lived signed
 * download URL (see signed-url.ts), matching the "no permanent public
 * fileUrl" requirement from Phase 0 amendment #3.
 */
export class LocalStorageProvider implements StorageProvider {
  constructor(private readonly baseDir: string) {}

  private resolvePath(storageKey: string): string {
    // storageKey is always generated by us (never derived from user input),
    // but guard against path traversal regardless.
    const normalized = path.normalize(storageKey).replace(/^(\.\.[/\\])+/, "");
    return path.join(this.baseDir, normalized);
  }

  async saveFile({
    buffer,
    userId,
    originalName,
  }: {
    buffer: Buffer;
    userId: string;
    originalName: string;
  }): Promise<SavedFile> {
    const ext = path.extname(originalName).toLowerCase();
    const storageKey = `resumes/${userId}/${randomUUID()}${ext}`;
    const fullPath = this.resolvePath(storageKey);

    await mkdir(path.dirname(fullPath), { recursive: true });
    await writeFile(fullPath, buffer);

    const sha256 = createHash("sha256").update(buffer).digest("hex");
    return { storageKey, sizeBytes: buffer.length, sha256 };
  }

  async readFile(storageKey: string): Promise<Buffer> {
    const fullPath = this.resolvePath(storageKey);
    if (!existsSync(fullPath)) {
      throw new Error(`Storage object not found: ${storageKey}`);
    }
    return readFile(fullPath);
  }

  async deleteFile(storageKey: string): Promise<void> {
    const fullPath = this.resolvePath(storageKey);
    if (existsSync(fullPath)) {
      await unlink(fullPath);
    }
  }
}
