import type { JobProvider, NormalizedJob, ProviderSearchQuery } from "./provider.interface.js";

interface DemoRawJob {
  id: string;
  title: string;
  company: string;
  location: string;
  country: string;
  workMode: "remote" | "hybrid" | "onsite";
  employmentType: "full_time" | "part_time" | "contract" | "internship";
  experienceMin: number;
  experienceMax: number;
  salaryMin: number;
  salaryMax: number;
  description: string;
  responsibilities: string[];
  requirements: string[];
  preferredQualifications: string[];
  skills: string[];
  postedDaysAgo: number;
}

const DEMO_JOBS: DemoRawJob[] = [
  {
    id: "demo-001",
    title: "Full Stack Developer",
    company: "Northwind Labs",
    location: "Bangalore, India",
    country: "India",
    workMode: "remote",
    employmentType: "full_time",
    experienceMin: 1,
    experienceMax: 3,
    salaryMin: 800000,
    salaryMax: 1400000,
    description:
      "Northwind Labs is looking for a Full Stack Developer to build and maintain our core product using React and Node.js.",
    responsibilities: [
      "Build features across the stack, from React UI to Node/Express APIs",
      "Collaborate with product and design on new feature specs",
      "Write and maintain automated tests",
    ],
    requirements: ["React", "Node.js", "TypeScript", "REST APIs"],
    preferredQualifications: ["MongoDB", "Docker"],
    skills: ["React", "Node.js", "TypeScript", "MongoDB", "REST APIs"],
    postedDaysAgo: 2,
  },
  {
    id: "demo-002",
    title: "MERN Stack Developer",
    company: "Northwind Labs",
    location: "Bangalore, India",
    country: "India",
    workMode: "remote",
    employmentType: "full_time",
    experienceMin: 1,
    experienceMax: 3,
    salaryMin: 800000,
    salaryMax: 1400000,
    description:
      "We're hiring a MERN stack engineer to join our growing engineering team and help ship new product features.",
    responsibilities: [
      "Develop features across MongoDB, Express, React, and Node",
      "Participate in code review and technical design discussions",
    ],
    requirements: ["React", "Node.js", "MongoDB", "Express"],
    preferredQualifications: ["TypeScript", "Docker"],
    skills: ["React", "Node.js", "MongoDB", "Express", "TypeScript"],
    postedDaysAgo: 3,
  },
  {
    id: "demo-003",
    title: "React Developer",
    company: "Bluefin Analytics",
    location: "Remote",
    country: "India",
    workMode: "remote",
    employmentType: "full_time",
    experienceMin: 0,
    experienceMax: 2,
    salaryMin: 600000,
    salaryMax: 1000000,
    description:
      "Bluefin Analytics builds dashboards for financial data teams. We need a React developer to own our frontend.",
    responsibilities: ["Build data-dense dashboard UIs in React", "Work closely with a small design team"],
    requirements: ["React", "JavaScript", "CSS"],
    preferredQualifications: ["TypeScript", "Recharts or D3"],
    skills: ["React", "JavaScript", "TypeScript", "CSS"],
    postedDaysAgo: 5,
  },
  {
    id: "demo-004",
    title: "Senior Backend Engineer",
    company: "Cascade Systems",
    location: "San Francisco, CA",
    country: "United States",
    workMode: "hybrid",
    employmentType: "full_time",
    experienceMin: 6,
    experienceMax: 10,
    salaryMin: 170000,
    salaryMax: 220000,
    description:
      "Cascade Systems is looking for a senior backend engineer to lead design of our next-generation payments infrastructure.",
    responsibilities: [
      "Design and own core payments services",
      "Mentor mid-level engineers",
      "Drive architecture decisions for scale and reliability",
    ],
    requirements: ["Node.js", "Distributed systems", "PostgreSQL", "8+ years experience"],
    preferredQualifications: ["Kubernetes", "Kafka"],
    skills: ["Node.js", "PostgreSQL", "Kubernetes", "Kafka", "System Design"],
    postedDaysAgo: 1,
  },
  {
    id: "demo-005",
    title: "Frontend Engineer",
    company: "Lumen Health",
    location: "Austin, TX",
    country: "United States",
    workMode: "onsite",
    employmentType: "full_time",
    experienceMin: 2,
    experienceMax: 5,
    salaryMin: 110000,
    salaryMax: 145000,
    description:
      "Lumen Health builds patient-facing tools for clinics. Join our frontend team to improve care coordination software.",
    responsibilities: ["Build accessible, performant patient-facing UI", "Collaborate with clinicians on UX"],
    requirements: ["React", "TypeScript", "Accessibility (a11y)"],
    preferredQualifications: ["Next.js", "Testing Library"],
    skills: ["React", "TypeScript", "Accessibility", "Next.js"],
    postedDaysAgo: 8,
  },
  {
    id: "demo-006",
    title: "Software Engineer, Full Stack",
    company: "Lumen Health",
    location: "Austin, TX",
    country: "United States",
    workMode: "hybrid",
    employmentType: "full_time",
    experienceMin: 2,
    experienceMax: 6,
    salaryMin: 115000,
    salaryMax: 150000,
    description:
      "We're expanding our engineering team at Lumen Health — full stack engineers welcome across frontend and backend.",
    responsibilities: ["Ship features spanning React frontend and Node backend services"],
    requirements: ["React", "Node.js", "PostgreSQL"],
    preferredQualifications: ["TypeScript"],
    skills: ["React", "Node.js", "PostgreSQL", "TypeScript"],
    postedDaysAgo: 8,
  },
  {
    id: "demo-007",
    title: "Junior Frontend Developer",
    company: "Pixel Forge Studio",
    location: "Remote",
    country: "United Kingdom",
    workMode: "remote",
    employmentType: "full_time",
    experienceMin: 0,
    experienceMax: 1,
    salaryMin: 28000,
    salaryMax: 36000,
    description:
      "Pixel Forge Studio is a small creative agency looking for a junior developer eager to grow their frontend skills.",
    responsibilities: ["Implement designs in HTML/CSS/JS", "Support senior devs on client projects"],
    requirements: ["HTML", "CSS", "JavaScript"],
    preferredQualifications: ["React basics"],
    skills: ["HTML", "CSS", "JavaScript", "React"],
    postedDaysAgo: 12,
  },
  {
    id: "demo-008",
    title: "DevOps Engineer",
    company: "Cascade Systems",
    location: "San Francisco, CA",
    country: "United States",
    workMode: "hybrid",
    employmentType: "full_time",
    experienceMin: 3,
    experienceMax: 7,
    salaryMin: 140000,
    salaryMax: 180000,
    description:
      "Own the CI/CD pipeline and cloud infrastructure that powers Cascade's payments platform.",
    responsibilities: ["Manage Kubernetes clusters", "Improve CI/CD pipelines", "On-call rotation"],
    requirements: ["Kubernetes", "Docker", "AWS", "Terraform"],
    preferredQualifications: ["Datadog", "Prometheus"],
    skills: ["Kubernetes", "Docker", "AWS", "Terraform"],
    postedDaysAgo: 4,
  },
  {
    id: "demo-009",
    title: "Product Engineer",
    company: "Bluefin Analytics",
    location: "Remote",
    country: "India",
    workMode: "remote",
    employmentType: "full_time",
    experienceMin: 2,
    experienceMax: 5,
    salaryMin: 1200000,
    salaryMax: 2000000,
    description:
      "Work across the stack at a small, fast-moving fintech analytics startup, shipping directly to customers.",
    responsibilities: ["Own features end to end", "Talk to customers directly", "Ship weekly"],
    requirements: ["React", "Node.js", "SQL"],
    preferredQualifications: ["TypeScript", "GraphQL"],
    skills: ["React", "Node.js", "SQL", "TypeScript", "GraphQL"],
    postedDaysAgo: 1,
  },
  {
    id: "demo-010",
    title: "Backend Developer (Node.js)",
    company: "Northwind Labs",
    location: "Bangalore, India",
    country: "India",
    workMode: "remote",
    employmentType: "full_time",
    experienceMin: 2,
    experienceMax: 4,
    salaryMin: 900000,
    salaryMax: 1500000,
    description: "Focus purely on backend services — APIs, queues, and data layer for our core product.",
    responsibilities: ["Build and maintain REST APIs", "Design database schemas", "Own background job processing"],
    requirements: ["Node.js", "Express", "MongoDB", "Redis"],
    preferredQualifications: ["BullMQ", "Docker"],
    skills: ["Node.js", "Express", "MongoDB", "Redis"],
    postedDaysAgo: 6,
  },
  {
    id: "demo-011",
    title: "Staff Software Engineer",
    company: "Meridian Cloud",
    location: "New York, NY",
    country: "United States",
    workMode: "hybrid",
    employmentType: "full_time",
    experienceMin: 8,
    experienceMax: 15,
    salaryMin: 220000,
    salaryMax: 280000,
    description: "Meridian Cloud needs a staff engineer to drive technical strategy across multiple product teams.",
    responsibilities: ["Set technical direction", "Cross-team architecture reviews", "Mentor senior engineers"],
    requirements: ["10+ years experience", "Distributed systems", "System design"],
    preferredQualifications: ["Go", "Kubernetes"],
    skills: ["System Design", "Distributed Systems", "Kubernetes", "Go"],
    postedDaysAgo: 3,
  },
  {
    id: "demo-012",
    title: "QA Automation Engineer",
    company: "Lumen Health",
    location: "Austin, TX",
    country: "United States",
    workMode: "remote",
    employmentType: "full_time",
    experienceMin: 2,
    experienceMax: 5,
    salaryMin: 100000,
    salaryMax: 130000,
    description: "Build and maintain automated test suites for our patient-facing and clinician-facing products.",
    responsibilities: ["Write E2E and integration tests", "Maintain CI test infrastructure"],
    requirements: ["Playwright or Cypress", "JavaScript/TypeScript"],
    preferredQualifications: ["CI/CD experience"],
    skills: ["Playwright", "Cypress", "TypeScript", "Testing"],
    postedDaysAgo: 10,
  },
  {
    id: "demo-013",
    title: "Mobile Engineer (React Native)",
    company: "Pixel Forge Studio",
    location: "Remote",
    country: "United Kingdom",
    workMode: "remote",
    employmentType: "contract",
    experienceMin: 2,
    experienceMax: 6,
    salaryMin: 40000,
    salaryMax: 60000,
    description: "Contract role building a React Native app for a client in the fitness space.",
    responsibilities: ["Build cross-platform mobile features", "Integrate with REST APIs"],
    requirements: ["React Native", "JavaScript"],
    preferredQualifications: ["TypeScript", "Expo"],
    skills: ["React Native", "JavaScript", "TypeScript"],
    postedDaysAgo: 15,
  },
  {
    id: "demo-014",
    title: "Data Engineer",
    company: "Bluefin Analytics",
    location: "Remote",
    country: "India",
    workMode: "remote",
    employmentType: "full_time",
    experienceMin: 3,
    experienceMax: 6,
    salaryMin: 1400000,
    salaryMax: 2200000,
    description: "Build data pipelines feeding our financial analytics dashboards.",
    responsibilities: ["Build ETL pipelines", "Maintain data warehouse", "Optimize query performance"],
    requirements: ["Python", "SQL", "Airflow"],
    preferredQualifications: ["Spark", "dbt"],
    skills: ["Python", "SQL", "Airflow", "Spark"],
    postedDaysAgo: 7,
  },
  {
    id: "demo-015",
    title: "Engineering Manager",
    company: "Meridian Cloud",
    location: "New York, NY",
    country: "United States",
    workMode: "hybrid",
    employmentType: "full_time",
    experienceMin: 7,
    experienceMax: 12,
    salaryMin: 200000,
    salaryMax: 250000,
    description: "Lead a team of 6-8 engineers building Meridian's core cloud platform.",
    responsibilities: ["1:1s and career growth for reports", "Sprint planning", "Cross-functional coordination"],
    requirements: ["5+ years engineering", "2+ years management"],
    preferredQualifications: ["Prior startup experience"],
    skills: ["Engineering Management", "System Design", "Leadership"],
    postedDaysAgo: 4,
  },
  {
    id: "demo-016",
    title: "Full Stack Engineer",
    company: "Meridian Cloud",
    location: "New York, NY",
    country: "United States",
    workMode: "hybrid",
    employmentType: "full_time",
    experienceMin: 1,
    experienceMax: 3,
    salaryMin: 120000,
    salaryMax: 155000,
    description: "Join Meridian's platform team building internal tools and customer-facing dashboards.",
    responsibilities: ["Build internal tools in React/Node", "Collaborate with platform and infra teams"],
    requirements: ["React", "Node.js", "TypeScript"],
    preferredQualifications: ["GraphQL", "PostgreSQL"],
    skills: ["React", "Node.js", "TypeScript", "GraphQL", "PostgreSQL"],
    postedDaysAgo: 2,
  },
  {
    id: "demo-017",
    title: "Platform Engineer",
    company: "Cascade Systems",
    location: "San Francisco, CA",
    country: "United States",
    workMode: "remote",
    employmentType: "full_time",
    experienceMin: 4,
    experienceMax: 8,
    salaryMin: 160000,
    salaryMax: 200000,
    description: "Build internal developer platform tooling used by 40+ engineers at Cascade Systems.",
    responsibilities: ["Build internal CLI and deployment tooling", "Improve developer experience"],
    requirements: ["Go", "Kubernetes", "Terraform"],
    preferredQualifications: ["Node.js"],
    skills: ["Go", "Kubernetes", "Terraform"],
    postedDaysAgo: 9,
  },
  {
    id: "demo-018",
    title: "Full Stack Developer",
    company: "Lumen Health",
    location: "Austin, TX",
    country: "United States",
    workMode: "remote",
    employmentType: "full_time",
    experienceMin: 1,
    experienceMax: 3,
    salaryMin: 105000,
    salaryMax: 135000,
    description: "Lumen Health is reposting this full stack role — same team, refreshed requirements.",
    responsibilities: ["Build features across React frontend and Node backend"],
    requirements: ["React", "Node.js", "TypeScript"],
    preferredQualifications: ["PostgreSQL"],
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL"],
    postedDaysAgo: 0,
  },
  {
    id: "demo-019",
    title: "UI Engineer",
    company: "Pixel Forge Studio",
    location: "Remote",
    country: "United Kingdom",
    workMode: "remote",
    employmentType: "part_time",
    experienceMin: 1,
    experienceMax: 4,
    salaryMin: 20000,
    salaryMax: 30000,
    description: "Part-time UI engineer role for a design-forward creative studio.",
    responsibilities: ["Build polished, animated UI components", "Pair with designers on interactions"],
    requirements: ["CSS", "JavaScript", "Animation libraries"],
    preferredQualifications: ["Framer Motion", "React"],
    skills: ["CSS", "JavaScript", "React", "Framer Motion"],
    postedDaysAgo: 20,
  },
  {
    id: "demo-020",
    title: "Site Reliability Engineer",
    company: "Meridian Cloud",
    location: "New York, NY",
    country: "United States",
    workMode: "hybrid",
    employmentType: "full_time",
    experienceMin: 4,
    experienceMax: 9,
    salaryMin: 165000,
    salaryMax: 210000,
    description: "Keep Meridian's cloud platform reliable at scale — on-call, incident response, and reliability work.",
    responsibilities: ["Own incident response process", "Improve observability", "Capacity planning"],
    requirements: ["Kubernetes", "Prometheus", "Distributed systems"],
    preferredQualifications: ["Go"],
    skills: ["Kubernetes", "Prometheus", "Distributed Systems", "Go"],
    postedDaysAgo: 5,
  },
];

export class DemoJobProvider implements JobProvider {
  readonly name = "demo";
  readonly schemaVersion = "1.0.0";

  async searchJobs(query: ProviderSearchQuery): Promise<unknown[]> {
    let results = DEMO_JOBS;
    if (query.keywords) {
      const kw = query.keywords.toLowerCase();
      results = results.filter(
        (job) => job.title.toLowerCase().includes(kw) || job.skills.some((s) => s.toLowerCase().includes(kw)),
      );
    }
    return query.limit ? results.slice(0, query.limit) : results;
  }

  normalizeJob(raw: unknown): NormalizedJob {
    const job = raw as DemoRawJob;
    const postedAt = new Date(Date.now() - job.postedDaysAgo * 24 * 60 * 60 * 1000);

    return {
      sourceJobId: job.id,
      title: job.title,
      company: job.company,
      location: job.location,
      country: job.country,
      workMode: job.workMode,
      employmentType: job.employmentType,
      experienceMin: job.experienceMin,
      experienceMax: job.experienceMax,
      salaryMin: job.salaryMin,
      salaryMax: job.salaryMax,
      salaryCurrency: job.country === "India" ? "INR" : job.country === "United Kingdom" ? "GBP" : "USD",
      description: job.description,
      responsibilities: job.responsibilities,
      requirements: job.requirements,
      preferredQualifications: job.preferredQualifications,
      skills: job.skills,
      applyUrl: `https://demo-jobs.example.com/apply/${job.id}`,
      sourceUrl: `https://demo-jobs.example.com/jobs/${job.id}`,
      postedAt,
    };
  }
}
